# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

eslint:
  enabled: true
  config_file: .eslintrc.ts

exclude_paths:
  - ".github"
  - ".vscode"
  - "postman-collections/**/*"
  - "src/database/**/*"
  - "src/docs/**/*"
  - "src/middlewares/**/*"
  - "src/models/**/*"
  - "src/app.ts"
  - "src/server.ts"
  - "**/*interface*.*"
  - "tests/**/*"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.env"
  - ".gitignore"
  - ".prettierignore"
  - ".prettierrc"
  - "jest.config.ts"
  - "LICENSE"
  - "README.md"
