# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

eslint:
  enabled: true
  config_file: .eslintrc.ts

exclude_paths:
  - '.github'
  - '.vscode'
  - 'LICENSE'
  - 'README.md'
  - '**/*.json'
  - '**/prettier*'
  - 'jest.config.js'
  - 'postman-collections'
  - 'tests/**/*'
  - 'src/data/**/*'
  - 'src/docs/**/*'
  - 'src/middlewares/**/*'
  - 'src/models/**/*'
  - 'src/utils/**/*'
  - 'app.ts'
  - 'server.ts'
