# https://docs.codeclimate.com/docs/advanced-configuration

exclude_patterns:
  - 'src/database/'
  - 'src/docs/'
  - 'src/middlewares/'
  - 'src/models/'
  - 'tests/'
  - 'dist/'
  - '**/node_modules/'
