# https://docs.codecov.com/docs/codecov-yaml

ignore:
  - 'src/data'
  - 'src/docs'
  - 'src/middlewares'
  - 'src/models'
  - 'src/routes'
  - 'src/utils'
  - 'src/app.ts'
  - 'src/server.ts'
  - 'tests'

coverage:
  status:
    project:
      controllers:
        paths:
          - 'src/controllers'
    patch:
      default:
        informational: true
