# Validate your repository YAML
# https://docs.codecov.com/docs/codecov-yaml#validate-your-repository-yaml
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

# Ignoring Paths
# https://docs.codecov.com/docs/ignoring-paths
# The pattern folder/* will not match recursively in the folder.
# Please use this folder/**/*, which will exclude all files within the given folder.
ignore:
  - 'src/data'
  - 'src/models'
  - 'src/utils'
  - 'src/app.ts'
  - 'src/server.ts'
  - 'tests'

coverage:
  status:
    # Splitting up projects
    # https://docs.codecov.com/docs/commit-status#splitting-up-projects-example
    project:
      controllers:
        paths:
          - 'src/controllers'
      routes:
        paths:
          - 'src/routes'
    patch:
      default:
        informational: true
