const playerStub = {
    all: [
        {
            id: 'ccffacd3-04bb-47fc-b296-3626cc9830e4',
            firstName: 'Damián',
            middleName: 'Emiliano',
            lastName: 'Martínez',
            dateOfBirth: '1992-09-02T00:00:00.000Z',
            squadNumber: 23,
            position: 'Goalkeeper',
            abbrPosition: 'GK',
            team: 'Aston Villa FC',
            league: 'Premier League',
            starting11: true,
        },
        {
            id: 'e2631558-c4a9-4bfe-a256-20c012e3058e',
            firstName: 'Nahuel',
            middleName: null,
            lastName: 'Molina',
            dateOfBirth: '1998-04-06T00:00:00.000Z',
            squadNumber: 26,
            position: 'Right-Back',
            abbrPosition: 'RB',
            team: 'Atlético Madrid',
            league: 'La Liga',
            starting11: true,
        },
        {
            id: '15d270eb-f2f3-48b0-929c-4118bb83deab',
            firstName: 'Cristian',
            middleName: 'Gabriel',
            lastName: 'Romero',
            dateOfBirth: '1998-04-27T00:00:00.000Z',
            squadNumber: 13,
            position: 'Centre-Back',
            abbrPosition: 'CB',
            team: 'Tottenham Hotspur',
            league: 'Premier League',
            starting11: true,
        },
        {
            id: 'e917c225-62ca-4104-ab11-97c285c1fab7',
            firstName: 'Nicolás',
            middleName: 'Hernán Gonzalo',
            lastName: 'Otamendi',
            dateOfBirth: '1988-02-12T00:00:00.000Z',
            squadNumber: 19,
            position: 'Centre-Back',
            abbrPosition: 'CB',
            team: 'SL Benfica',
            league: 'Liga Portugal',
            starting11: true,
        },
        {
            id: '2a720525-5fa0-4ba3-91ca-29e57ef9f617',
            firstName: 'Nicolás',
            middleName: 'Alejandro',
            lastName: 'Tagliafico',
            dateOfBirth: '1992-08-31T00:00:00.000Z',
            squadNumber: 3,
            position: 'Left-Back',
            abbrPosition: 'LB',
            team: 'Olympique Lyon',
            league: 'Ligue 1',
            starting11: true,
        },
        {
            id: '35a047e2-8e66-4d0b-997e-655e044e0f4c',
            firstName: 'Ángel',
            middleName: 'Fabián',
            lastName: 'Di María',
            dateOfBirth: '1988-02-14T00:00:00.000Z',
            squadNumber: 11,
            position: 'Right Winger',
            abbrPosition: 'LW',
            team: 'SL Benfica',
            league: 'Liga Portugal',
            starting11: true,
        },
        {
            id: 'e459624c-c0bb-4109-a8f8-ced2d94211b7',
            firstName: 'Rodrigo',
            middleName: 'Javier',
            lastName: 'de Paul',
            dateOfBirth: '1994-05-24T00:00:00.000Z',
            squadNumber: 7,
            position: 'Central Midfield',
            abbrPosition: 'CM',
            team: 'Atlético Madrid',
            league: 'La Liga',
            starting11: true,
        },
        {
            id: 'c8973352-48c1-4c48-b389-746ff9c3a157',
            firstName: 'Enzo',
            middleName: 'Jeremías',
            lastName: 'Fernández',
            dateOfBirth: '2001-01-17T00:00:00.000Z',
            squadNumber: 24,
            position: 'Central Midfield',
            abbrPosition: 'CM',
            team: 'Chelsea FC',
            league: 'Premier League',
            starting11: true,
        },
        {
            id: '92ad0ed8-f7ac-4c69-93a1-fe5149b913ab',
            firstName: 'Alexis',
            middleName: null,
            lastName: 'Mac Allister',
            dateOfBirth: '1998-12-24T00:00:00.000Z',
            squadNumber: 20,
            position: 'Central Midfield',
            abbrPosition: 'CM',
            team: 'Liverpool FC',
            league: 'Premier League',
            starting11: true,
        },
        {
            id: '4293d9c7-8561-42c3-9ec3-f04e6691ff76',
            firstName: 'Lionel',
            middleName: 'Andrés',
            lastName: 'Messi',
            dateOfBirth: '1987-06-24T00:00:00.000Z',
            squadNumber: 10,
            position: 'Right Winger',
            abbrPosition: 'RW',
            team: 'Inter Miami CF',
            league: 'Major League Soccer',
            starting11: true,
        },
        {
            id: 'b704a5ce-b08a-4ef9-bba4-fbab1e7a8e03',
            firstName: 'Julián',
            middleName: null,
            lastName: 'Álvarez',
            dateOfBirth: '2000-01-31T00:00:00.000Z',
            squadNumber: 9,
            position: 'Centre-Forward',
            abbrPosition: 'CF',
            team: 'Manchester City',
            league: 'Premier League',
            starting11: true,
        },
    ],
    new: {
        firstName: 'Leandro',
        middleName: 'Daniel',
        lastName: 'Paredes',
        dateOfBirth: '1994-06-29T00:00:00.000Z',
        squadNumber: 5,
        position: 'Defensive Midfield',
        abbrPosition: 'DM',
        team: 'AS Roma',
        league: 'Serie A',
        starting11: false,
    },
    findBySquadNumber(squadNumber: number): any | null {
        return this.all.find((player: { squadNumber: number }) => player.squadNumber === squadNumber) || null;
    },
};

export default playerStub;
